# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-11 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_phone', models.CharField(max_length=16)),
                ('u_username', models.CharField(max_length=32)),
                ('u_sex', models.BooleanField()),
                ('u_birth_year', models.IntegerField(max_length=4, null=True)),
                ('u_location', models.CharField(max_length=64, null=True)),
                ('u_hobby', models.CharField(max_length=64, null=True)),
                ('u_instructions', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_user_id', models.IntegerField()),
                ('p_location', models.CharField(max_length=32)),
                ('p_min_distance', models.IntegerField(default=5, max_length=1)),
                ('p_max_distance', models.IntegerField(default=20, max_length=3)),
                ('p_min_dating_age', models.IntegerField(default=15)),
                ('p_max_dating_age', models.IntegerField(default=30)),
                ('p_dating_Sex', models.BooleanField()),
                ('p_vibration', models.BooleanField(default=True)),
            ],
        ),
    ]
