# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_icon',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='u_is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='u_token',
            field=models.IntegerField(default=1296000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_phone',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_username',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='p_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.User'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
