# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20190112_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_birth_year',
            field=models.IntegerField(max_length=4, null=True, verbose_name='出生年'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_hobby',
            field=models.CharField(max_length=64, null=True, verbose_name='爱好'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_icon',
            field=models.CharField(max_length=256, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_instructions',
            field=models.CharField(max_length=128, null=True, verbose_name='个人说明'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_location',
            field=models.CharField(max_length=64, null=True, verbose_name='常住地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_sex',
            field=models.BooleanField(max_length=8, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_token',
            field=models.IntegerField(default=1296000, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_username',
            field=models.CharField(max_length=32, unique=True, verbose_name='昵称'),
        ),
    ]
