# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20190114_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_sex',
            field=models.BooleanField(default=1, max_length=8, verbose_name='性别'),
        ),
    ]
