# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-15 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_auto_20190115_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_birth_day',
            field=models.IntegerField(default=1, max_length=4, verbose_name='出生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_birth_month',
            field=models.IntegerField(default=1, max_length=8, verbose_name='出生月'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_birth_year',
            field=models.IntegerField(default=2000, max_length=8, verbose_name='出生年'),
        ),
    ]
